Repository krisode/beauty-at-home, pull requests merged in 2021-01, with the labels that each got.

#12 Feature/be/hien ht/authentication 04
  ApplicationCore/Services/AccountService.cs
  ApplicationCore/Services/IService.cs
  BeautyAtHome/Authorization/RequiredRoleHandler.cs
  BeautyAtHome/Authorization/RequiredRolePolicyProvider.cs
  BeautyAtHome/Authorization/RequiredRoleRequirement.cs
  BeautyAtHome/Controllers/AuthController.cs
  BeautyAtHome/Controllers/ServiceController.cs
  BeautyAtHome/Startup.cs
  BeautyAtHome/Utils/AutoMapperProfile.cs
  BeautyAtHome/Utils/Constants.cs
  BeautyAtHome/Utils/JwtTokenProvider.cs
  BeautyAtHome/ViewModels/AuthViewModel.cs
  BeautyAtHome/ViewModels/ServiceViewModel.cs
  BeautyAtHome/appsettings.json
  Infrastructure/Contexts/Account.cs
  Infrastructure/Contexts/AccountInSalon.cs
  Infrastructure/Contexts/Address.cs
  Infrastructure/Contexts/BeautyServiceProviderContext.cs
  Infrastructure/Contexts/Booking.cs
  Infrastructure/Contexts/BookingActivity.cs
  Infrastructure/Contexts/BookingDetail.cs
  Infrastructure/Contexts/FeedBack.cs
  Infrastructure/Contexts/Gallery.cs
  Infrastructure/Contexts/Image.cs
  Infrastructure/Contexts/Salon.cs
  Infrastructure/Contexts/Service.cs
  Infrastructure/Contexts/ServiceInCombo.cs
  Infrastructure/Contexts/ServiceType.cs
  Keys/firebase_admin_sdk.json
Labels: bug, enhancement

#14 Feature/be/hien ht/paging [HienHT] [GIT] Delete change (file csproj)
  .gitignore
  ApplicationCore/ApplicationCore.csproj
  ApplicationCore/Services/AccountService.cs
  ApplicationCore/Services/BeautyServicesService.cs
  ApplicationCore/Services/IBaseService.cs
  ApplicationCore/Services/IService.cs
  BeautyAtHome/Controllers/ServiceController.cs
  BeautyAtHome/Startup.cs
  BeautyAtHome/Utils/PagingSupport.cs
Labels: bug

#15 Update ServiceController, add GetQueryList(multiple where)
  ApplicationCore/Services/BeautyServicesService.cs
  ApplicationCore/Services/IService.cs
  BeautyAtHome/Controllers/ServiceController.cs
  BeautyAtHome/Utils/AutoMapperProfile.cs
  BeautyAtHome/Utils/Constants.cs
  BeautyAtHome/ViewModels/ServiceViewModel.cs
  Infrastructure/Interfaces/IRepository.cs
  Infrastructure/Interfaces/Implements/Repository.cs
Labels: enhancement

#17 Feature/be/refactor base code paging fixed/hien ht
  ApplicationCore/Services/AccountService.cs
  ApplicationCore/Services/BeautyServicesService.cs
  ApplicationCore/Services/IBaseService.cs
  ApplicationCore/Services/IService.cs
  BeautyAtHome/Controllers/AuthController.cs
  BeautyAtHome/Controllers/ServiceController.cs
  BeautyAtHome/Startup.cs
  BeautyAtHome/Utils/AutoMapperProfile.cs
  BeautyAtHome/Utils/PagingSupport.cs
  BeautyAtHome/ViewModels/AuthViewModel.cs
  BeautyAtHome/ViewModels/ServiceViewModel.cs
  Infrastructure/Contexts/BeautyServiceProviderContext.cs
  Infrastructure/Contexts/Service.cs
  Infrastructure/Contexts/ServiceType.cs
  Infrastructure/Interfaces/IRepository.cs
  Infrastructure/Interfaces/IUnitOfWork.cs
  Infrastructure/Interfaces/Implements/Repository.cs
  Infrastructure/Interfaces/Implements/UnitOfWork.cs
  Infrastructure/Repositories/AccountRepository.cs
  Infrastructure/Repositories/ServiceRepository.cs
Labels: enhancement
